const TeamData = [

    {
        teamClass:"team-member",
        memberImage:"img/team/ceo.jpg",
        memberImageAlt: "CEO",
        memberName: "Mosharaf Hossain",
        memberDesc: "CEO & Founder",
        memberFBLink: "https://www.facebook.com/mshosn",
        memberTWLink: "https://www.instagram.com/md.rashidh/",
        memberLNLink: "https://www.linkedin.com/in/mosharafh/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/tofael.webp",
        memberImageAlt: "Tofael",
        memberName: "Md. Tofael Ahmed",
        memberDesc: "Full-Stack Web Developer & Manager",
        memberFBLink: "https://www.facebook.com/tofaelahmedcse",
        memberTWLink: "https://www.instagram.com/ahamedtofiel/",
        memberLNLink: "https://www.linkedin.com/in/tofaelahmedcse/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/team/naiem.jpg",
        memberImageAlt: "Naiem",
        memberName: "Muhammad Naiem",
        memberDesc: "Front-End Designer & React Developer",
        memberFBLink: "https://www.facebook.com/frontenddeveloper1999",
        memberTWLink: "https://www.instagram.com/frontenddeveloper1999/",
        memberLNLink: "https://www.linkedin.com/in/muhammad-naiem-937525202/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/team/jakia.jpg",
        memberImageAlt: "jakia",
        memberName: "Jakia Sultana",
        memberDesc: "Admin manager and Back-End developer",
        memberFBLink: "https://www.facebook.com/jakiarj.jakia",
        memberTWLink: "https://www.instagram.com/jakiarj.jakia/?hl=en",
        memberLNLink: "https://www.linkedin.com/in/jakia-sultana-707a0a191/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/team/Kamruzzaman-Khondakar.jpg",
        memberImageAlt: "Kamruzzaman Khondakar",
        memberName: "Kamruzzaman Khondakar",
        memberDesc: "SR. Back-End developer",
        memberFBLink: "https://www.facebook.com/kamruzzaman4",
        memberTWLink: "https://www.instagram.com/kamruzzaman4/",
        memberLNLink: "https://www.linkedin.com/in/kamruzzaman4/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member instagram-remove linkdin-remove",
        memberImage:"img/team/shawkot.jpg",
        memberImageAlt: "Aliul Haque",
        memberName: "Aliul Haque",
        memberDesc: "Business Development Consultant.",
        memberFBLink: "https://www.facebook.com/aliul.haque",
        // eslint-disable-next-line no-script-url
        memberTWLink: "javascript:void(0)",
        // eslint-disable-next-line no-script-url
        memberLNLink: "javascript:void(0)",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/team/sojib1.webp",
        memberImageAlt: "sojib",
        memberName: "Sojib Hasan",
        memberDesc: "Front-End Executive",
        memberFBLink: "https://www.facebook.com/sojibHasan.fb",
        memberTWLink: "https://twitter.com/SojibHa70172560",
        memberLNLink: "https://www.linkedin.com/in/sojib-hasan-a943a3205/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member instagram-remove",
        memberImage:"img/team/anik.jpg",
        memberImageAlt: "anik",
        memberName: "Ahanf Anik",
        memberDesc: "Front-End Executive",
        memberFBLink: "https://www.facebook.com/anik.hossen.790256",
        // eslint-disable-next-line no-script-url
        memberTWLink: "javascript:void(0)",
        memberLNLink: "https://www.linkedin.com/in/shazzad-anik-b07027205/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member social-account",
        memberImage:"img/team/al-amin.jpg",
        memberImageAlt: "al-amin",
        memberName: "Muhammad Al-Amin",
        memberDesc: "Front-End Executive",
        memberFBLink: "https://www.facebook.com/muhammad1254",
        memberTWLink: "https://www.instagram.com/muhammadalamin24034/",
        memberLNLink: "https://www.linkedin.com/in/muhammad-al-amin-b59653205/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/team/Rony.webp",
        memberImageAlt: "Rony",
        memberName: "Robiul Islam Rony",
        memberDesc: "Back-End Executive",
        memberFBLink: "https://www.facebook.com/mdrobiulislamronycse",
        memberTWLink: "https://www.instagram.com/mdrobiulislamronycse",
        memberLNLink: "https://www.linkedin.com/in/mdrobiulislamronycse",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/team/khayer.jpg",
        memberImageAlt: "khayer",
        memberName: "Md. Monjoor Kahyer",
        memberDesc: "Trainer IT and Executive HR",
        memberFBLink: "https://web.facebook.com/monjoor.khayer",
        memberTWLink: "https://www.instagram.com/mmkhayer/",
        memberLNLink: "https://www.linkedin.com/in/md-monjoor-khayer-03414319/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/team/asad.png",
        memberImageAlt: "asad",
        memberName: "Mohammad Assad Kari",
        memberDesc: "SEO & Digital Marketing Executive",
        memberFBLink: "https://www.facebook.com/Assad.kari/",
        memberTWLink: "https://www.instagram.com/mohammad_assad_kari/",
        memberLNLink: "https://www.linkedin.com/in/mohammad-assad-kari-541b63248/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member linkdin-remove",
        memberImage:"img/team/Taj-Ahmmed.jpg",
        memberImageAlt: "Taj Ahmmed",
        memberName: "Taj Ahmmed",
        memberDesc: "UI designer",
        memberFBLink: "https://www.facebook.com/mdtaj.ahmmed.56",
        memberTWLink: "https://www.instagram.com/taj_ahmmed_/",
        // eslint-disable-next-line no-script-url
        memberLNLink: "javascript:void(0)",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member instagram-remove",
        memberImage:"img/team/sazzad.png",
        memberImageAlt: "Sazzad Hossain Shojib",
        memberName: "Sazzad Hossain Shojib",
        memberDesc: "BDE & Content Writing expert",
        memberFBLink: "https://www.facebook.com/shajjadhossain.shojib",
        // eslint-disable-next-line no-script-url
        memberTWLink: "javascript:void(0)",
        memberLNLink: "https://www.linkedin.com/in/sazzad-hossain-shojib-885267249/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member instagram-remove",
        memberImage:"img/team/mamunur.jpg",
        memberImageAlt: "Mamunur Rashid",
        memberName: "Mamunur Rashid",
        memberDesc: "BDE & SEO expert",
        memberFBLink: "https://www.facebook.com/profile.php?id=100035034292677",
        // eslint-disable-next-line no-script-url
        memberTWLink: "javascript:void(0)",
        memberLNLink: "https://www.linkedin.com/in/seo-expert-digital-merketer/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member",
        memberImage:"img/team/muktia.jpg",
        memberImageAlt: "Muktia Akter",
        memberName: "Muktia Akter",
        memberDesc: "Digital Marketer & HR Admin Executive",
        memberFBLink: "https://www.facebook.com/jennifer.muktia.3",
        memberTWLink: "https://www.instagram.com/jennifermuktia/",
        memberLNLink: "https://www.linkedin.com/in/muktia-akhter-a555b0219/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member instagram-remove linkdin-remove",
        memberImage:"img/team/masud.webp",
        memberImageAlt: "masud",
        memberName: "Masud Rana",
        memberDesc: "Affiliate Marketing Expert and Video Editor",
        memberFBLink: "https://www.facebook.com/masudcpc6",
        // eslint-disable-next-line no-script-url
        memberTWLink: "javascript:void(0)",
        // eslint-disable-next-line no-script-url
        memberLNLink: "javascript:void(0)",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member social-account",
        memberImage:"img/team/salma.jpg",
        memberImageAlt: "salma",
        memberName: "Salma Ahamed",
        memberDesc: "Business development & Lead generation Executive",
        memberFBLink: "https://www.facebook.com/salmaahamed1097",
        memberTWLink: "/",
        memberLNLink: "https://www.linkedin.com/in/salma-ahamed-7275b5238/",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    },
    {
        teamClass:"team-member social-account",
        memberImage:"img/team/shurela.jpg",
        memberImageAlt: "shurela",
        memberName: "Shurela Yeasmin Arna",
        memberDesc: "Business Development & Lead generation Executive",
        memberFBLink: "https://www.facebook.com/Shurelayeasmin08",
        memberTWLink: "https://www.instagram.com/shurela_yeasmin",
        memberLNLink: "https://www.linkedin.com/in/shurela-yeasmin",
        memberFBIco: "svgs/Facebook.svg",
        memberTWIco: "svgs/instagram.svg" ,
        memberLNIco: "svgs/LinkedIn.svg",
        memberFBAlt: "facebook",
        memberTWAlt: "twitter",
        memberLNAlt: "linkedin",
    }
]

export default TeamData;